spring:
  profiles:
    active: local
  h2.console:
      enabled: true
      path: '/admin/console'
  datasource:
    url: 'jdbc:h2:file:./H2Database'
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
